Common components
Feldmanager/feldmanagerclient pull request #2
Opened 2020-10-07 18:03 UTC by thelittlecitizen18

navbar & tabbar

2020-10-08 12:21 UTC, thelittlecitizen19 requested changes

2020-10-08 12:21 UTC, thelittlecitizen19 commented on src/Components/CommonComponents/Tabs/Test1.jsx
> +import React from 'react';
move all imports to the top of the page

2020-10-08 12:21 UTC, thelittlecitizen19 commented on src/Components/CommonComponents/Tabs/Test1.jsx
> +function ClassNames(props) {
change the name to more indicative name

2020-10-08 12:21 UTC, thelittlecitizen19 commented on src/Components/CommonComponents/Tabs/Test1.jsx
> +import React from 'react';
seperate components between files

2020-10-08 12:21 UTC, thelittlecitizen19 commented on src/Components/CommonComponents/Tabs/Test1.jsx
> +export default function FullWidthTabs() {
use only one export default in file, you can use export with { } to export multipal objects by name

2020-10-08 12:21 UTC, thelittlecitizen19 commented on src/Components/CommonComponents/Navbar/Navbar.jsx
> +                <a className="navbar-brand" href="#">Feldmanager</a>
get feldmanager string as props property

2020-10-08 20:10 UTC, thelittlecitizen18 commented on src/Components/CommonComponents/Navbar/Navbar.jsx
> +                        {navbarList.map((item)=>{
done

2020-10-08 20:11 UTC, thelittlecitizen18 commented on src/Components/CommonComponents/Navbar/Navbar.jsx
> +                            return(
done

2020-10-11 06:50 UTC, thelittlecitizen19 approved these changes

2020-10-11 20:06 UTC, closed without merging